[2024-06-19T14:52:10.023+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T14:52:10.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailtest.send_email manual__2024-06-19T14:51:46.986165+00:00 [queued]>
[2024-06-19T14:52:10.042+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailtest.send_email manual__2024-06-19T14:51:46.986165+00:00 [queued]>
[2024-06-19T14:52:10.042+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T14:52:10.050+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_email> on 2024-06-19 14:51:46.986165+00:00
[2024-06-19T14:52:10.054+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T14:52:10.054+0000] {standard_task_runner.py:63} INFO - Started process 76 to run task
[2024-06-19T14:52:10.055+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emailtest', 'send_email', 'manual__2024-06-19T14:51:46.986165+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/emailtest.py', '--cfg-path', '/tmp/tmpnssn8w6t']
[2024-06-19T14:52:10.055+0000] {standard_task_runner.py:91} INFO - Job 163: Subtask send_email
[2024-06-19T14:52:10.079+0000] {task_command.py:426} INFO - Running <TaskInstance: emailtest.send_email manual__2024-06-19T14:51:46.986165+00:00 [running]> on host d20a658c1fdb
[2024-06-19T14:52:10.125+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='liviataina.ltab@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emailtest' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T14:51:46.986165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T14:51:46.986165+00:00'
[2024-06-19T14:52:10.125+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T14:52:10.138+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-06-19T14:52:10.139+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-19T14:52:12.776+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T14:52:12.777+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.starttls()
  File "/usr/local/lib/python3.12/smtplib.py", line 771, in starttls
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
[2024-06-19T14:52:12.793+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=emailtest, task_id=send_email, run_id=manual__2024-06-19T14:51:46.986165+00:00, execution_date=20240619T145146, start_date=20240619T145210, end_date=20240619T145212
[2024-06-19T14:52:12.812+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 163 for task send_email (STARTTLS extension not supported by server.; 76)
[2024-06-19T14:52:12.837+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T14:52:12.861+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T14:52:12.863+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
