[2024-06-19T14:51:52.314+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T14:51:52.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailtest.task4 manual__2024-06-19T14:51:46.986165+00:00 [queued]>
[2024-06-19T14:51:52.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailtest.task4 manual__2024-06-19T14:51:46.986165+00:00 [queued]>
[2024-06-19T14:51:52.333+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T14:51:52.342+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task4> on 2024-06-19 14:51:46.986165+00:00
[2024-06-19T14:51:52.345+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T14:51:52.346+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2024-06-19T14:51:52.346+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emailtest', 'task4', 'manual__2024-06-19T14:51:46.986165+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/emailtest.py', '--cfg-path', '/tmp/tmp79wvvkbl']
[2024-06-19T14:51:52.347+0000] {standard_task_runner.py:91} INFO - Job 161: Subtask task4
[2024-06-19T14:51:52.372+0000] {task_command.py:426} INFO - Running <TaskInstance: emailtest.task4 manual__2024-06-19T14:51:46.986165+00:00 [running]> on host d20a658c1fdb
[2024-06-19T14:51:52.416+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='liviataina.ltab@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emailtest' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T14:51:46.986165+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T14:51:46.986165+00:00'
[2024-06-19T14:51:52.417+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T14:51:52.431+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-19T14:51:52.432+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-06-19T14:51:52.442+0000] {subprocess.py:86} INFO - Output:
[2024-06-19T14:51:52.444+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-19T14:51:52.444+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T14:51:52.452+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-19T14:51:52.456+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=emailtest, task_id=task4, run_id=manual__2024-06-19T14:51:46.986165+00:00, execution_date=20240619T145146, start_date=20240619T145152, end_date=20240619T145152
[2024-06-19T14:51:52.470+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 161 for task task4 (Bash command failed. The command returned a non-zero exit code 1.; 70)
[2024-06-19T14:51:52.479+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T14:51:52.493+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T14:51:52.494+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
