[2024-06-20T12:55:35.901+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T12:55:35.916+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailtest20.task4 manual__2024-06-20T12:55:30.696545+00:00 [queued]>
[2024-06-20T12:55:35.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailtest20.task4 manual__2024-06-20T12:55:30.696545+00:00 [queued]>
[2024-06-20T12:55:35.921+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T12:55:35.931+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task4> on 2024-06-20 12:55:30.696545+00:00
[2024-06-20T12:55:35.934+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=76) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T12:55:35.935+0000] {standard_task_runner.py:63} INFO - Started process 77 to run task
[2024-06-20T12:55:35.935+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emailtest20', 'task4', 'manual__2024-06-20T12:55:30.696545+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/emailtest.py', '--cfg-path', '/tmp/tmpg6igw9fp']
[2024-06-20T12:55:35.936+0000] {standard_task_runner.py:91} INFO - Job 304: Subtask task4
[2024-06-20T12:55:35.961+0000] {task_command.py:426} INFO - Running <TaskInstance: emailtest20.task4 manual__2024-06-20T12:55:30.696545+00:00 [running]> on host 255e965b3d80
[2024-06-20T12:55:36.007+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='liviataina.ltab@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emailtest20' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T12:55:30.696545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T12:55:30.696545+00:00'
[2024-06-20T12:55:36.008+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T12:55:36.016+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-20T12:55:36.016+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-06-20T12:55:36.023+0000] {subprocess.py:86} INFO - Output:
[2024-06-20T12:55:36.024+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-20T12:55:36.025+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T12:55:36.031+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-20T12:55:36.033+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=emailtest20, task_id=task4, run_id=manual__2024-06-20T12:55:30.696545+00:00, execution_date=20240620T125530, start_date=20240620T125535, end_date=20240620T125536
[2024-06-20T12:55:36.041+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 304 for task task4 (Bash command failed. The command returned a non-zero exit code 1.; 77)
[2024-06-20T12:55:36.067+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T12:55:36.084+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T12:55:36.087+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
