[2024-06-20T11:34:06.885+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T11:34:06.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailtest.send_email manual__2024-06-20T11:33:29.073762+00:00 [queued]>
[2024-06-20T11:34:06.920+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailtest.send_email manual__2024-06-20T11:33:29.073762+00:00 [queued]>
[2024-06-20T11:34:06.920+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-20T11:34:06.929+0000] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): send_email> on 2024-06-20 11:33:29.073762+00:00
[2024-06-20T11:34:06.933+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T11:34:06.933+0000] {standard_task_runner.py:63} INFO - Started process 106 to run task
[2024-06-20T11:34:06.934+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emailtest', 'send_email', 'manual__2024-06-20T11:33:29.073762+00:00', '--job-id', '237', '--raw', '--subdir', 'DAGS_FOLDER/emailtest.py', '--cfg-path', '/tmp/tmpy1acafm2']
[2024-06-20T11:34:06.935+0000] {standard_task_runner.py:91} INFO - Job 237: Subtask send_email
[2024-06-20T11:34:06.965+0000] {task_command.py:426} INFO - Running <TaskInstance: emailtest.send_email manual__2024-06-20T11:33:29.073762+00:00 [running]> on host d075f3895514
[2024-06-20T11:34:07.009+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='liviataina.ltab@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emailtest' AIRFLOW_CTX_TASK_ID='send_email' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T11:33:29.073762+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T11:33:29.073762+00:00'
[2024-06-20T11:34:07.010+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T11:34:07.023+0000] {base.py:84} INFO - Using connection ID 'smtp_default' for task execution.
[2024-06-20T11:34:07.023+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-20T11:34:10.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T11:34:10.344+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.starttls()
  File "/usr/local/lib/python3.12/smtplib.py", line 771, in starttls
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
[2024-06-20T11:34:10.359+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=emailtest, task_id=send_email, run_id=manual__2024-06-20T11:33:29.073762+00:00, execution_date=20240620T113329, start_date=20240620T113406, end_date=20240620T113410
[2024-06-20T11:34:10.376+0000] {base.py:84} INFO - Using connection ID 'smtp_default' for task execution.
[2024-06-20T11:34:10.376+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-20T11:34:13.694+0000] {base.py:84} INFO - Using connection ID 'smtp_default' for task execution.
[2024-06-20T11:34:13.695+0000] {email.py:271} INFO - Email alerting: attempt 1
[2024-06-20T11:34:17.308+0000] {taskinstance.py:879} ERROR - Failed to send email to: ['liviataina.ltab@gmail.com']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2676, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2701, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.starttls()
  File "/usr/local/lib/python3.12/smtplib.py", line 771, in starttls
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1063, in _email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.starttls()
  File "/usr/local/lib/python3.12/smtplib.py", line 771, in starttls
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 877, in _handle_failure
    task_instance.email_alert(error, failure_context["task"])
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3163, in email_alert
    _email_alert(task_instance=self, exception=exception, task=task)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1065, in _email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
           ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py", line 279, in send_mime_email
    smtp_conn.starttls()
  File "/usr/local/lib/python3.12/smtplib.py", line 771, in starttls
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: STARTTLS extension not supported by server.
[2024-06-20T11:34:17.344+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 237 for task send_email (STARTTLS extension not supported by server.; 106)
[2024-06-20T11:34:17.366+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T11:34:17.395+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T11:34:17.397+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
