[2024-06-20T13:34:24.723+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T13:34:24.737+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailtestallsuccess.task4 manual__2024-06-20T13:34:19.990530+00:00 [queued]>
[2024-06-20T13:34:24.742+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailtestallsuccess.task4 manual__2024-06-20T13:34:19.990530+00:00 [queued]>
[2024-06-20T13:34:24.742+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T13:34:24.750+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task4> on 2024-06-20 13:34:19.990530+00:00
[2024-06-20T13:34:24.754+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=493) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T13:34:24.755+0000] {standard_task_runner.py:63} INFO - Started process 494 to run task
[2024-06-20T13:34:24.755+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emailtestallsuccess', 'task4', 'manual__2024-06-20T13:34:19.990530+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/emailtestallsuccess.py', '--cfg-path', '/tmp/tmpl0ym0y90']
[2024-06-20T13:34:24.756+0000] {standard_task_runner.py:91} INFO - Job 339: Subtask task4
[2024-06-20T13:34:24.781+0000] {task_command.py:426} INFO - Running <TaskInstance: emailtestallsuccess.task4 manual__2024-06-20T13:34:19.990530+00:00 [running]> on host 3f2e9f854293
[2024-06-20T13:34:24.825+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='liviataina.ltab@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emailtestallsuccess' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T13:34:19.990530+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T13:34:19.990530+00:00'
[2024-06-20T13:34:24.826+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T13:34:24.834+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-20T13:34:24.834+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-06-20T13:34:24.841+0000] {subprocess.py:86} INFO - Output:
[2024-06-20T13:34:24.842+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-20T13:34:24.842+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T13:34:24.848+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-20T13:34:24.850+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=emailtestallsuccess, task_id=task4, run_id=manual__2024-06-20T13:34:19.990530+00:00, execution_date=20240620T133419, start_date=20240620T133424, end_date=20240620T133424
[2024-06-20T13:34:24.858+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 339 for task task4 (Bash command failed. The command returned a non-zero exit code 1.; 494)
[2024-06-20T13:34:24.888+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T13:34:24.921+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T13:34:24.922+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
