[2024-06-20T12:59:16.374+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T12:59:16.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailtest21.task4 manual__2024-06-20T12:59:11.255470+00:00 [queued]>
[2024-06-20T12:59:16.393+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailtest21.task4 manual__2024-06-20T12:59:11.255470+00:00 [queued]>
[2024-06-20T12:59:16.393+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T12:59:16.404+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task4> on 2024-06-20 12:59:11.255470+00:00
[2024-06-20T12:59:16.408+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T12:59:16.409+0000] {standard_task_runner.py:63} INFO - Started process 70 to run task
[2024-06-20T12:59:16.409+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emailtest21', 'task4', 'manual__2024-06-20T12:59:11.255470+00:00', '--job-id', '313', '--raw', '--subdir', 'DAGS_FOLDER/emailtest.py', '--cfg-path', '/tmp/tmpahb6l7xq']
[2024-06-20T12:59:16.409+0000] {standard_task_runner.py:91} INFO - Job 313: Subtask task4
[2024-06-20T12:59:16.436+0000] {task_command.py:426} INFO - Running <TaskInstance: emailtest21.task4 manual__2024-06-20T12:59:11.255470+00:00 [running]> on host 22bade8d9d37
[2024-06-20T12:59:16.485+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='liviataina.ltab@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emailtest21' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T12:59:11.255470+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T12:59:11.255470+00:00'
[2024-06-20T12:59:16.485+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T12:59:16.493+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-20T12:59:16.493+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-06-20T12:59:16.501+0000] {subprocess.py:86} INFO - Output:
[2024-06-20T12:59:16.503+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-20T12:59:16.503+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T12:59:16.508+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-20T12:59:16.511+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=emailtest21, task_id=task4, run_id=manual__2024-06-20T12:59:11.255470+00:00, execution_date=20240620T125911, start_date=20240620T125916, end_date=20240620T125916
[2024-06-20T12:59:16.520+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 313 for task task4 (Bash command failed. The command returned a non-zero exit code 1.; 70)
[2024-06-20T12:59:16.541+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T12:59:16.558+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T12:59:16.559+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
