[2024-06-19T11:38:13.874+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T11:38:13.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: second_trigger_dag.task1 manual__2024-06-19T11:38:12.596699+00:00 [queued]>
[2024-06-19T11:38:13.891+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: second_trigger_dag.task1 manual__2024-06-19T11:38:12.596699+00:00 [queued]>
[2024-06-19T11:38:13.891+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T11:38:13.900+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task1> on 2024-06-19 11:38:12.596699+00:00
[2024-06-19T11:38:13.903+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=789) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T11:38:13.904+0000] {standard_task_runner.py:63} INFO - Started process 791 to run task
[2024-06-19T11:38:13.904+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'second_trigger_dag', 'task1', 'manual__2024-06-19T11:38:12.596699+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/triggerdag2.py', '--cfg-path', '/tmp/tmp80uzmouy']
[2024-06-19T11:38:13.905+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask task1
[2024-06-19T11:38:13.930+0000] {task_command.py:426} INFO - Running <TaskInstance: second_trigger_dag.task1 manual__2024-06-19T11:38:12.596699+00:00 [running]> on host 61c28926c6e1
[2024-06-19T11:38:13.982+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='second_trigger_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T11:38:12.596699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T11:38:12.596699+00:00'
[2024-06-19T11:38:13.982+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T11:38:13.993+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-19T11:38:13.994+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-06-19T11:38:14.000+0000] {subprocess.py:86} INFO - Output:
[2024-06-19T11:38:14.001+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-19T11:38:14.001+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T11:38:14.007+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-19T11:38:14.009+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=second_trigger_dag, task_id=task1, run_id=manual__2024-06-19T11:38:12.596699+00:00, execution_date=20240619T113812, start_date=20240619T113813, end_date=20240619T113814
[2024-06-19T11:38:14.018+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task task1 (Bash command failed. The command returned a non-zero exit code 1.; 791)
[2024-06-19T11:38:14.036+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T11:38:14.051+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-19T11:38:14.053+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
