[2024-06-21T12:38:18.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T12:38:18.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branchtest.branch_task manual__2024-06-21T12:38:16.198996+00:00 [queued]>
[2024-06-21T12:38:18.562+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branchtest.branch_task manual__2024-06-21T12:38:16.198996+00:00 [queued]>
[2024-06-21T12:38:18.563+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T12:38:18.570+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-06-21 12:38:16.198996+00:00
[2024-06-21T12:38:18.574+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1131) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T12:38:18.575+0000] {standard_task_runner.py:63} INFO - Started process 1132 to run task
[2024-06-21T12:38:18.575+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'branchtest', 'branch_task', 'manual__2024-06-21T12:38:16.198996+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/brachs.py', '--cfg-path', '/tmp/tmpls_dbdef']
[2024-06-21T12:38:18.576+0000] {standard_task_runner.py:91} INFO - Job 401: Subtask branch_task
[2024-06-21T12:38:18.605+0000] {task_command.py:426} INFO - Running <TaskInstance: branchtest.branch_task manual__2024-06-21T12:38:16.198996+00:00 [running]> on host 55c563b9c0dc
[2024-06-21T12:38:18.657+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branchtest' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T12:38:16.198996+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T12:38:16.198996+00:00'
[2024-06-21T12:38:18.657+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T12:38:18.665+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-21T12:38:18.672+0000] {python.py:237} INFO - Done. Returned value was: even_task
[2024-06-21T12:38:18.672+0000] {branch.py:36} INFO - Branch into even_task
[2024-06-21T12:38:18.672+0000] {skipmixin.py:178} INFO - Following branch even_task
[2024-06-21T12:38:18.683+0000] {skipmixin.py:246} INFO - Skipping tasks [('odd_task', -1)]
[2024-06-21T12:38:18.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T12:38:18.708+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=branchtest, task_id=branch_task, run_id=manual__2024-06-21T12:38:16.198996+00:00, execution_date=20240621T123816, start_date=20240621T123818, end_date=20240621T123818
[2024-06-21T12:38:18.748+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-21T12:38:18.780+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-21T12:38:18.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
