[2024-06-19T14:23:58.837+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T14:23:58.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: emailtest.task4 manual__2024-06-19T14:23:52.941585+00:00 [queued]>
[2024-06-19T14:23:58.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: emailtest.task4 manual__2024-06-19T14:23:52.941585+00:00 [queued]>
[2024-06-19T14:23:58.857+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T14:23:58.865+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task4> on 2024-06-19 14:23:52.941585+00:00
[2024-06-19T14:23:58.870+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=357) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T14:23:58.870+0000] {standard_task_runner.py:63} INFO - Started process 358 to run task
[2024-06-19T14:23:58.871+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'emailtest', 'task4', 'manual__2024-06-19T14:23:52.941585+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/emailtest.py', '--cfg-path', '/tmp/tmp99m32l6z']
[2024-06-19T14:23:58.871+0000] {standard_task_runner.py:91} INFO - Job 124: Subtask task4
[2024-06-19T14:23:58.897+0000] {task_command.py:426} INFO - Running <TaskInstance: emailtest.task4 manual__2024-06-19T14:23:52.941585+00:00 [running]> on host c743c3172e67
[2024-06-19T14:23:58.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='liviataina.ltab@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='emailtest' AIRFLOW_CTX_TASK_ID='task4' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T14:23:52.941585+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T14:23:52.941585+00:00'
[2024-06-19T14:23:58.945+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T14:23:58.953+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-19T14:23:58.953+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'exit 1']
[2024-06-19T14:23:58.960+0000] {subprocess.py:86} INFO - Output:
[2024-06-19T14:23:58.961+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-19T14:23:58.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T14:23:58.967+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-19T14:23:58.971+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=emailtest, task_id=task4, run_id=manual__2024-06-19T14:23:52.941585+00:00, execution_date=20240619T142352, start_date=20240619T142358, end_date=20240619T142358
[2024-06-19T14:23:58.979+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 124 for task task4 (Bash command failed. The command returned a non-zero exit code 1.; 358)
[2024-06-19T14:23:59.003+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T14:23:59.039+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T14:23:59.042+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
