[2024-06-24T12:00:33.803+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-24T12:00:33.812+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: httpsensor.check_api manual__2024-06-24T12:00:32.891237+00:00 [queued]>
[2024-06-24T12:00:33.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: httpsensor.check_api manual__2024-06-24T12:00:32.891237+00:00 [queued]>
[2024-06-24T12:00:33.817+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-24T12:00:33.824+0000] {taskinstance.py:2330} INFO - Executing <Task(HttpSensor): check_api> on 2024-06-24 12:00:32.891237+00:00
[2024-06-24T12:00:33.828+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=438) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-24T12:00:33.829+0000] {standard_task_runner.py:63} INFO - Started process 439 to run task
[2024-06-24T12:00:33.829+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'httpsensor', 'check_api', 'manual__2024-06-24T12:00:32.891237+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/sensors.py', '--cfg-path', '/tmp/tmpz83n5doc']
[2024-06-24T12:00:33.830+0000] {standard_task_runner.py:91} INFO - Job 437: Subtask check_api
[2024-06-24T12:00:33.855+0000] {task_command.py:426} INFO - Running <TaskInstance: httpsensor.check_api manual__2024-06-24T12:00:32.891237+00:00 [running]> on host e3e60e62d12c
[2024-06-24T12:00:33.900+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='httpsensor' AIRFLOW_CTX_TASK_ID='check_api' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T12:00:32.891237+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-24T12:00:32.891237+00:00'
[2024-06-24T12:00:33.901+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-24T12:00:33.909+0000] {baseoperator.py:400} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-06-24T12:00:33.909+0000] {http.py:137} INFO - Poking: entries
[2024-06-24T12:00:33.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-24T12:00:33.919+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 164, in execute
    super().execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 158, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/sensors/http.py", line 139, in poke
    response = hook.run(
               ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 167, in run
    session = self.get_conn(headers)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/http/hooks/http.py", line 108, in get_conn
    conn = self.get_connection(self.http_conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `connection` isn't defined
[2024-06-24T12:00:33.921+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=httpsensor, task_id=check_api, run_id=manual__2024-06-24T12:00:32.891237+00:00, execution_date=20240624T120032, start_date=20240624T120033, end_date=20240624T120033
[2024-06-24T12:00:33.928+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 437 for task check_api (The conn_id `connection` isn't defined; 439)
[2024-06-24T12:00:33.961+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-24T12:00:34.001+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-24T12:00:34.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
